In [2]:
import numpy as np 
list=[[1,2,3],[4,5,6]]
np_array=np.array(list)
print(np_array)

[[1 2 3]
 [4 5 6]]


In [3]:
list2=[[1],[2]]
np_array2=np.array(list2)
print(np_array2)

[[1]
 [2]]


In [4]:
addition=np_array+np_array2
print(addition)

[[2 3 4]
 [6 7 8]]


In [6]:
import numpy as np
a = np.array([[1,2,3]]) #creating a numpy n-dimensional array
a.shape

(1, 3)