In [ ]:
import numpy as np
#with 2by3 and 1by2 matrix can be added because of broadcasting 
array1=np.array([1,2,3])
array2=np.array([4,5,6])
addition=array1+array2
print(addition)

[5 7 9]


In [ ]:
#Multiply Matrix by a scalar.
#in mtrix multiplication the number of columns in the first matrix must be different from the number of rows in the second matrix.
#when rows and column are same matrix multiplication cannot be done and all other can be done 
scalar_value=4
array=np.array([[1,2],
                [3,4]])

muntiply= scalar_value * array
print(muntiply)


#0 means column and 1 means row 


# for vertical stacking column and column should be same and for horizontal stacking rows and rows should be same 

[[ 4  8]
 [12 16]]


In [4]:
# An identity matrix is a square matrix (same number of rows and columns) with:

# 1s on the main diagonal (from top-left to bottom-right).
# 0s everywhere else.

# Create an Identity matrix.

identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Convert 1D array to 3D array.
array_1d=np.array([1, 2, 3, 4, 5, 6])
array_3d = array_1d.reshape(2, 3, 1)
print(array_3d)


[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [ ]:
# Write a python code to convert data type from float to integer.
int_array=np.array([1,2,3,4,5])
float_array=int_array.astype(float)
print(float_array)
print(float_array.dtype)

[1. 2. 3. 4. 5.]
float64


In [9]:
# Getting the positions (indexes) where elements of 2 numpy arrays match by using numpy
array1=np.array([1,2,3,4,5,5,8,9])
array2=np.array([0,2,4,6,2,6,5,9])
matching_indices=np.where(array1==array2)
print(matching_indices)

(array([1, 7]),)


In [ ]:
# Replace all odd numbers in the given array with -1
# exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# In NumPy, you can use a boolean array (True/False) inside square brackets [] to select elements from the original array.
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise_1[exercise_1 % 2 != 0] = -1
print(exercise_1)



[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# Get the positions where elements of a and b match
# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

matching_indices = np.where(a == b)

print("Matching values:",matching_indices)


Matching values: (array([2, 4, 6]),)


In [13]:
# To find the indices of the maximum values in each column, use numpy.argmax():
matrix = np.array([[1, 5, 3],
                   [4, 2, 6],
                   [7, 8, 9]])

max_indices = np.argmax(matrix, axis=0)
print("Indices of max values in each column:", max_indices)


Indices of max values in each column: [2 2 2]


In [ ]:
# To find the maximum number from each column in a NumPy matrix (2D array), you can use the numpy.max() function with the appropriate axis parameter.
matrix = np.array([[1, 5, 3],
                   [4, 2, 6],
                   [7, 8, 9]])
print("Original matrix:\n", matrix)

# Find maximum in each column
max_per_column = np.max(matrix, axis=0)

print("\nMaximum value in each column:", max_per_column)

